# Generated by Django 5.0.4 on 2024-05-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product18_remove_product_price_product_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product18',
        ),
        migrations.AddField(
            model_name='product',
            name='MENUNA',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
