# Generated by Django 5.0.4 on 2024-05-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_product18_product_menuna_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIDEO18',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('LINK', models.CharField(max_length=200, null=True)),
                ('Mota', models.CharField(max_length=200, null=True)),
                ('digital', models.BooleanField(default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='LINK',
        ),
        migrations.RemoveField(
            model_name='product',
            name='MENUNA',
        ),
    ]
