# Generated by Django 5.0.4 on 2024-05-07 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_video18_remove_product_link_remove_product_menuna'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oder',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OderItem',
            new_name='OrderItem',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date_oder',
            new_name='date_order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='Oder',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Oder',
            new_name='Order',
        ),
    ]
